openapi: 3.0.0
info:
  title: Text Analyzer API
  version: 1.0.0
paths:
  /api/analyze:
    post:
      summary: Analyze text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                input:
                  type: string
                  description: The text input to analyze
                  example: "test input"
                letterType:
                  type: string
                  enum: [Vowels, Consonants]
                  description: Type of letters to analyze
                  example: "Consonants"
              required:
                - input
                - letterType
      responses:
        '200':
          description: Analysis results
          content:
            application/json:
              schema:
                type: string
                minLength: 1
                maxLength: 1
                additionalProperties:
                  type: integer
